//
// Created by QinBu_Rua on 2025/9/24.
//

#ifndef AUTO_SORTING_MACHINE_AUTO_SORTING_MACHINE_H
#define AUTO_SORTING_MACHINE_AUTO_SORTING_MACHINE_H




#endif //AUTO_SORTING_MACHINE_AUTO_SORTING_MACHINE_H